#!/bin/bash

cmd="$1"
p=$(which "$cmd")

if [ ! -n "$p" ]; then
	>&2 echo "'$cmd' is not on PATH"
	exit 1
fi

l=$(readlink -f "$p")

if [ ! -f "$l" ]; then
	>&2 echo "'$cmd' resolved to $l but does not exist"
	exit 2
fi

echo $l
